export const API_LOADING = 'API_LOADING';
export const OPERATION_FAILED = 'OPERATION_FAILED';

/* Get Multiple DropDown Options*/
export const GET_MULTIPLEDROPDOWN_OPTIONS_SUCCESS = "GET_MULTIPLEDROPDOWN_OPTIONS_SUCCESS" 
export const SUBMIT_FROMDATA_SUCCESS = "SUBMIT_FROMDATA_SUCCESS"

/* Toggle Ant Design and Bootstrap */
export const TOGGLE_DESIGN_STYLE = "TOGGLE_DESIGN_STYLE"