export const API_LOADING = 'API_LOADING';
export const OPERATION_FAILED = 'OPERATION_FAILED';

/* Get Multiple DropDown Options*/
export const GET_MULTIPLEDROPDOWN_OPTIONS_SUCCESS = "GET_MULTIPLEDROPDOWN_OPTIONS_SUCCESS" 